/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2003In', 'model/NodeEdge'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2003In'), require('./NodeEdge'));
  } else {
    // Browser globals (root is window)
    if (!root.phonetworks) {
      root.phonetworks = {};
    }
    root.phonetworks.InlineResponse2003 = factory(root.phonetworks.ApiClient, root.phonetworks.InlineResponse2003In, root.phonetworks.NodeEdge);
  }
}(this, function(ApiClient, InlineResponse2003In, NodeEdge) {
  'use strict';




  /**
   * The InlineResponse2003 model module.
   * @module model/InlineResponse2003
   * @version 1.1.1
   */

  /**
   * Constructs a new <code>InlineResponse2003</code>.
   * @alias module:model/InlineResponse2003
   * @class
   * @param from {Array.<module:model/NodeEdge>} 
   * @param to {Array.<module:model/NodeEdge>} 
   * @param _in {Array.<module:model/InlineResponse2003In>} 
   * @param out {Array.<module:model/InlineResponse2003In>} 
   */
  var exports = function(from, to, _in, out) {
    var _this = this;

    _this['from'] = from;
    _this['to'] = to;
    _this['in'] = _in;
    _this['out'] = out;
  };

  /**
   * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('from')) {
        obj['from'] = ApiClient.convertToType(data['from'], [NodeEdge]);
      }
      if (data.hasOwnProperty('to')) {
        obj['to'] = ApiClient.convertToType(data['to'], [NodeEdge]);
      }
      if (data.hasOwnProperty('in')) {
        obj['in'] = ApiClient.convertToType(data['in'], [InlineResponse2003In]);
      }
      if (data.hasOwnProperty('out')) {
        obj['out'] = ApiClient.convertToType(data['out'], [InlineResponse2003In]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/NodeEdge>} from
   */
  exports.prototype['from'] = undefined;
  /**
   * @member {Array.<module:model/NodeEdge>} to
   */
  exports.prototype['to'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse2003In>} in
   */
  exports.prototype['in'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse2003In>} out
   */
  exports.prototype['out'] = undefined;



  return exports;
}));


